# Introduction to Numpy

In [ ]:
#import library

import numpy as np

In [4]:
#create an array of odd numbers
hamoye = np.array(2,3,5,7,9,11)

NameError: name 'np' is not defined

In [3]:
hamoye

NameError: name 'hamoye' is not defined

In [ ]:
import numpy as np

In [9]:
import numpy as np
hamoye = np.array([2,3,5,7,9,11])
print(hamoye)

type(hamoye)

hamoye[:3]

[ 2  3  5  7  9 11]


array([2, 3, 5])

In [10]:
hamoye[3:]

array([ 7,  9, 11])

In [12]:
hamoye[2:3]

array([5])

In [15]:
hamoye[4] = 26
hamoye

array([ 2,  3,  5,  7, 26, 11])

In [20]:
hamoye_2 = np.array([[1,3,5,7],[2,4,6,8]], float)
hamoye_2

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [21]:
hamoye_2[1,2]

6.0

In [22]:
hamoye_2[0,:]

array([1., 3., 5., 7.])

In [23]:
hamoye_2[-1:,-2:]

array([[6., 8.]])

In [24]:
hamoye_2.dtype

hamoye_2.shape
len(hamoye_2)

2

# the in statement for np arrays

In [25]:
23 in hamoye_2

False

In [26]:
hamoye_range = np.array(range(20), float)
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [27]:
hamoye_range = hamoye_range.reshape((5,4))
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [4]:
hamoye_range.shape

NameError: name 'hamoye_range' is not defined

In [1]:
hamoye_range = np.array(range(20), float.reshape(5,4)

SyntaxError: invalid syntax (<ipython-input-1-db6ff3c6fb78>, line 2)

In [2]:
  hamoye_range

NameError: name 'hamoye_range' is not defined

In [ ]:
a = np.array([1,2,3,4], float)

In [3]:
a.tolist()

NameError: name 'a' is not defined

In [5]:
import numpy as np
hamoye_2 = np.array([[1,3,5,7],[2,4,6,8]], float)
hamoye_2

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [6]:
hamoye = np.array([2,3,5,7,9,11])
hamoye_range = np.array(range(20), float)
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [9]:
hamoye_range = hamoye_range.reshape((5,4))
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [10]:
hamoye_range.shape

(5, 4)

In [12]:
a = np.array([1,2,3,4], float)
a.tolist()

[1.0, 2.0, 3.0, 4.0]

In [15]:
hamoye_range = np.array(range(20), float).reshape(5,4)
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [17]:
hamoye_range.transpose()

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [18]:
hamoye_range.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [1]:
import numpy as np
arr = [6,7,8,9]
arr

[6, 7, 8, 9]

In [2]:
np.random.random((2,3))

array([[0.75912363, 0.76641289, 0.50511313],
       [0.54550076, 0.14226581, 0.66614004]])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [8]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [9]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [11]:
c**d

array([[6.56100e+03, 3.27680e+04, 1.17649e+05],
       [1.00000e+00, 2.56000e+02, 2.18700e+03]])

In [12]:
d[1,0:2]

array([9., 8.])

In [13]:
d

array([[4., 5., 6.],
       [9., 8., 7.]])

In [14]:
d[0,2]

6.0

In [15]:
d[1,0:3]

array([9., 8., 7.])

In [16]:
d[1,2:]

array([7.])

In [17]:
d[1,1:]

array([8., 7.])

In [20]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [21]:
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [22]:
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [23]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [29]:
import pandas as pd
days = pd.Series(['monday', 'tuesday', 'wednesday'])
days

0       monday
1      tuesday
2    wednesday
dtype: object

In [4]:
import numpy as np
days_list = np.array(['monday', 'tuesday', 'wednesday'])
days_list

array(['monday', 'tuesday', 'wednesday'], dtype='<U9')

In [5]:
import pandas as pd
days_list = np.array(['monday', 'tuesday', 'wednesday'])
numpy_days = pd.series(days_list)
numpy_days

AttributeError: module 'pandas' has no attribute 'series'

In [6]:
import pandas as pd
days = pd.Series(['monday', 'tuesday', 'wednesday'])
days

0       monday
1      tuesday
2    wednesday
dtype: object

In [11]:
import pandas as pd
import numpy as np
days_list = np.array(['monday', 'tuesday', 'wednesday'])
numpy_days = pd.series(days_list)
print(numpy_days)

AttributeError: module 'pandas' has no attribute 'series'

In [12]:
days[0]

'monday'

In [13]:
days[2:]

2    wednesday
dtype: object

In [16]:
days[1]

'tuesday'

In [18]:
df_dict = {'Country':['Ghana','Kenya','Nigeria','Togo'],'Capital':['Accra','Nairobi','Abuja','Lome'],'Population':[10000,8500,35000,12000],'Age':[60,70,80,75]}
df = pd.dataframe(df_dict,index = [2,4,6,8])

AttributeError: module 'pandas' has no attribute 'dataframe'